from __future__ import annotations


DEMO_ANALYSIS_RUN = {
    "run_id": "run_backend_demo_seed",
    "generated_at": "2026-05-01T22:30:00+08:00",
    "source_batch": {
        "batch_id": "batch_backend_demo_seed",
        "source_type": "public_sample",
        "platforms": ["bilibili", "douyin", "weibo"],
        "record_count": 9,
    },
    "events": [
        {
            "id": "event_0001",
            "name": "电子榨菜",
            "aliases": ["电子榨菜", "下饭视频", "精神榨菜"],
            "summary": "系统根据多平台证据判断，电子榨菜近期集中传播，疑似最早来源于 bilibili（2026-04-28T09:20:00+08:00）。",
            "status": "complete",
            "heat_score": 0.91,
            "confidence": 0.84,
            "first_seen_time": "2026-04-28T09:20:00+08:00",
            "source_platform": "bilibili",
            "source_confidence": 0.84,
            "source_status": "probable",
            "representative_evidence_id": "evi_0001_01",
            "keyword_signals": [{"term": "电子榨菜", "frequency": 7, "burst_score": 0.72}],
            "explanation_status": "generated",
            "notes": None,
        },
        {
            "id": "event_0002",
            "name": "遥遥领先",
            "aliases": ["遥遥领先", "遥遥领先梗", "领先体"],
            "summary": "系统检测到遥遥领先存在传播趋势，但来源证据存在冲突，当前仅可判定为不确定。",
            "status": "partial",
            "heat_score": 0.78,
            "confidence": 0.56,
            "first_seen_time": "2026-04-29T11:15:00+08:00",
            "source_platform": "weibo",
            "source_confidence": 0.56,
            "source_status": "uncertain",
            "representative_evidence_id": "evi_0002_01",
            "keyword_signals": [{"term": "遥遥领先", "frequency": 5, "burst_score": 0.61}],
            "explanation_status": "generated",
            "notes": "来源候选分数接近，建议人工复核",
        },
        {
            "id": "event_0003",
            "name": "班味",
            "aliases": ["班味", "去班味", "上班味"],
            "summary": "班味已被识别为候选表达，但当前证据不足，暂无法给出可靠来源解释。",
            "status": "needs_review",
            "heat_score": 0.47,
            "confidence": 0.35,
            "first_seen_time": "2026-04-30T18:05:00+08:00",
            "source_platform": None,
            "source_confidence": None,
            "source_status": "insufficient_evidence",
            "representative_evidence_id": "evi_0003_01",
            "keyword_signals": [{"term": "班味", "frequency": 3, "burst_score": 0.38}],
            "explanation_status": "insufficient_context",
            "notes": "候选证据不足，待人工确认",
        },
    ],
    "evidence": [
        {
            "id": "evi_0001_01",
            "event_id": "event_0001",
            "raw_post_id": "raw_001",
            "platform": "bilibili",
            "snippet": "这期视频太适合吃饭看了，简直是我的电子榨菜。",
            "post_time": "2026-04-28T09:20:00+08:00",
            "url": "https://www.bilibili.com/video/demo-electronic-pickle",
            "relevance_score": 1.0,
            "source_score": 0.84,
            "is_source_candidate": True,
            "evidence_type": "timeline_anchor",
        },
        {
            "id": "evi_0001_02",
            "event_id": "event_0001",
            "raw_post_id": "raw_002",
            "platform": "douyin",
            "snippet": "睡前刷到这个合集，电子榨菜又续上了。",
            "post_time": "2026-04-28T13:05:00+08:00",
            "url": "https://www.douyin.com/video/demo-electronic-pickle",
            "relevance_score": 0.92,
            "source_score": 0.73,
            "is_source_candidate": True,
            "evidence_type": "text_match",
        },
        {
            "id": "evi_0001_03",
            "event_id": "event_0001",
            "raw_post_id": "raw_003",
            "platform": "weibo",
            "snippet": "求推荐新的电子榨菜，下饭视频库存告急。",
            "post_time": "2026-04-28T19:40:00+08:00",
            "url": "https://weibo.com/demo/electronic-pickle",
            "relevance_score": 0.88,
            "source_score": 0.66,
            "is_source_candidate": False,
            "evidence_type": "text_match",
        },
        {
            "id": "evi_0002_01",
            "event_id": "event_0002",
            "raw_post_id": "raw_004",
            "platform": "weibo",
            "snippet": "这个剪辑效果真的遥遥领先，评论区已经开始接龙。",
            "post_time": "2026-04-29T11:15:00+08:00",
            "url": "https://weibo.com/demo/far-ahead",
            "relevance_score": 0.81,
            "source_score": 0.56,
            "is_source_candidate": True,
            "evidence_type": "timeline_anchor",
        },
        {
            "id": "evi_0002_02",
            "event_id": "event_0002",
            "raw_post_id": "raw_005",
            "platform": "bilibili",
            "snippet": "弹幕全在刷遥遥领先，这个领先体也太万能了。",
            "post_time": "2026-04-29T12:02:00+08:00",
            "url": "https://www.bilibili.com/video/demo-far-ahead",
            "relevance_score": 0.79,
            "source_score": 0.54,
            "is_source_candidate": True,
            "evidence_type": "text_match",
        },
        {
            "id": "evi_0003_01",
            "event_id": "event_0003",
            "raw_post_id": "raw_006",
            "platform": "douyin",
            "snippet": "周五下班终于开始去班味，整个人都亮了。",
            "post_time": "2026-04-30T18:05:00+08:00",
            "url": "https://www.douyin.com/video/demo-work-smell",
            "relevance_score": 0.72,
            "source_score": 0.42,
            "is_source_candidate": True,
            "evidence_type": "timeline_anchor",
        },
    ],
    "trend_snapshots": [
        {
            "id": "snap_0001",
            "event_id": "event_0001",
            "snapshot_time": "2026-04-28T20:00:00+08:00",
            "heat_value": 0.95,
            "platform_breakdown": {"bilibili": 0.42, "douyin": 0.33, "weibo": 0.25},
            "sample_count": 3,
        },
        {
            "id": "snap_0002",
            "event_id": "event_0002",
            "snapshot_time": "2026-04-29T13:00:00+08:00",
            "heat_value": 0.76,
            "platform_breakdown": {"weibo": 0.52, "bilibili": 0.48},
            "sample_count": 2,
        },
        {
            "id": "snap_0003",
            "event_id": "event_0003",
            "snapshot_time": "2026-04-30T18:30:00+08:00",
            "heat_value": 0.41,
            "platform_breakdown": {"douyin": 1.0},
            "sample_count": 1,
        },
    ],
    "stats": {
        "raw_post_count": 9,
        "normalized_post_count": 9,
        "candidate_term_count": 18,
        "event_count": 3,
    },
}
